name: TestPlugin
version: 1.0
main: TestPlugin
api-version: 1.17
commands:
  testremove:
    description: "Tests removing a nearby entity."
    usage: "/testremove"
  testtimeout:
    description: "Tests the API timeout functionality."
    usage: "/testtimeout"
