name: TestPlugin
version: 1.0
main: TestPlugin
api-version: 1.17
commands:
  testremove:
    description: "Tests removing a nearby entity."
    usage: "/testremove"
  testtimeout:
    description: "Tests the API timeout functionality."
    usage: "/testtimeout"
  testgetonlineplayers:
    description: "Tests the getOnlinePlayers transformation."
    usage: "/testgetonlineplayers"
  testhighestblock:
    description: "Tests the getHighestBlockAt transformation."
    usage: "/testhighestblock"
  testvelocity:
    description: "Tests async setVelocity call"
    usage: "/testvelocity"
  testteleport:
    description: "Tests async teleport call"
    usage: "/testteleport"
